# SConstruct for src/vnm

Import('env')

lib_name='nebula_vnm'

# Sources to generate the library
source_files=[
	'Leases.cc',
	'FixedLeases.cc'
]

# Build library
env.StaticLibrary(lib_name, source_files)
